### PR TITLE
Added mediapicker3 support

### PR DESCRIPTION
**Pull request by nickh364**
Added mediapicker3 support for Umbraco 8.14 >

### CODE REVIEW

**Comment by dinc5150** [comment]
Thanks for the PR @nickh364 . I've gone through and its mostly tested OK, I'll just need to change the way you assign `$scope.model.value.shareImage` due to an issue with the PropertyValueConverter and some backwards compatibility. 

You've done the hard work though, so thanks!

**Comment by dinc5150** [comment]
P.S. If you'd like to try out the latest pre-release version, you can install it from the MyGet Feed - https://www.myget.org/feed/digital-momentum/package/nuget/MetaMomentum

**Comment by dinc5150** [comment]
@nickh364 , I have published your pull request in V1.2 to nuget and our.umbraco.com. 

Thanks for your contribution!

**Comment by nickh364** [comment]
@dinc5150 Thanks for letting me know.

**Pull request merged**
